os: power
dist: xenial
language: node_js
node_js:
  - stable
before_install:
- if [ "$TRAVIS_OS_NAME" == "power" ]; then wget https://github.com/ibmsoe/phantomjs/releases/download/2.1.1/phantomjs-2.1.1-linux-ppc64.tar.bz2; fi
- if [ "$TRAVIS_OS_NAME" == "power" ]; then bunzip2 phantomjs-2.1.1-linux-ppc64.tar.bz2; fi 
- if [ "$TRAVIS_OS_NAME" == "power" ]; then tar -xvf phantomjs-2.1.1-linux-ppc64.tar; fi
- if [ "$TRAVIS_OS_NAME" == "power" ]; then sudo cp phantomjs-2.1.1-linux-ppc64/bin/phantomjs /usr/bin/phantomjs; fi
sudo: false
